### ISSUE TITLE
Game says "Not Responding"

### ISSUE THREAD

**Issue by Dugoutboards** [Umbustado/UPSI#1]
When I start up the application I receive the latest update 1.0.0.3. When I try to install it the application shuts down automatically. I try to wait to see if it starts back up but no nothing happens. I have retried multiple times but it still never downloads the update. Also, When I try to change my name or Install Pavlov onto my oculus quest, freezes and says "Not Responding". It also says "please connect your quest". I would really appreciate some help!

[https://gyazo.com/10626a33d6e61fdb13128d16d56a7b0b](https://gyazo.com/10626a33d6e61fdb13128d16d56a7b0b)

**Comment by Umbustado** [comment]
It appears to freeze because it cannot detect your quest - this is normally due to either running on win7 or 8 which are now not supported by oculus drivers or not being in DEV mode or not accepting the USB debug connection from inside your quest.  The update normally does not restart UPSI once it is updated - the issue has been addressed
